name: Build ZMK firmware

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: zmkfirmware/zmk-build-arm:stable
    strategy:
      fail-fast: false
      matrix:
        include:
          - board: rpi_pico2/rp2350a/m33
            shield: sofle_pico_left
          - board: rpi_pico2/rp2350a/m33
            shield: sofle_pico_right
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: config

      - name: West Init
        run: west init -l config

      - name: West Update
        run: west update

      - name: West Zephyr export
        run: west zephyr-export

      - name: West Build
        run: |
          west build -s zmk/app -d build/${{ matrix.shield }} \
            -b "${{ matrix.board }}" \
            -- -DZMK_CONFIG="${GITHUB_WORKSPACE}/config" \
               -DSHIELD="${{ matrix.shield }}"

      - name: Rename artifact
        run: |
          mkdir -p artifacts
          cp build/${{ matrix.shield }}/zephyr/zmk.uf2 \
             artifacts/${{ matrix.shield }}-rpi_pico2.uf2

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.shield }}-firmware
          path: artifacts/*.uf2
